[tool.black]
line-length = 100
target-version = ["py313"]

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["apps"]

[tool.pylint.'MAIN']
load-plugins = "pylint.extensions.docparams"

[tool.pylint.'BASIC']
good-names = ["id", "pk", "db", "ok"]

[tool.pylint.'MESSAGES CONTROL']
disable = [
  "missing-docstring",
  "invalid-name",
  "too-few-public-methods",
  "too-many-arguments",
  "too-many-locals",
  "too-many-instance-attributes",
  "too-many-public-methods",
  "too-many-return-statements",
  "too-many-branches",
  "too-many-statements",
  "too-many-nested-blocks",
  "duplicate-code",
  "global-statement",
  "missing-raises-doc",
]

[tool.pylint.'TYPECHECK']
ignored-modules = ["sqlalchemy", "sqlmodel", "pytest"]

[tool.pylint.'FORMAT']
max-line-length = 100
