"""Pydantic schemas for API payloads."""

from .account import (
    AccountCreate,
    AccountRead,
    AccountUpdate,
    AccountWithBalance,
    ListAccountsQuery,
    ListAccountsResponse,
    LoanCreate,
    LoanRead,
    UpdateAccountPath,
)
from .category import (
    CategoryCreate,
    CategoryListResponse,
    CategoryPathParams,
    CategoryRead,
    CategoryUpdate,
    ListCategoriesQuery,
)
from .loan import (
    LoanCreateRequest,
    LoanEventListQuery,
    LoanEventRead,
    LoanScheduleQuery,
    LoanScheduleRead,
    LoanUpdate,
)
from .reporting import (
    MonthlyReportEntry,
    MonthlyReportQuery,
    MonthlyReportResponse,
    NetWorthHistoryQuery,
    NetWorthHistoryResponse,
    NetWorthPoint,
    TotalReportQuery,
    TotalReportRead,
    YearlyReportEntry,
    YearlyReportQuery,
    YearlyReportResponse,
)
from .transaction import (
    TransactionCreate,
    TransactionLegCreate,
    TransactionLegRead,
    TransactionListQuery,
    TransactionListResponse,
    TransactionRead,
)

__all__ = [
    "AccountCreate",
    "AccountRead",
    "AccountUpdate",
    "AccountWithBalance",
    "ListAccountsQuery",
    "ListAccountsResponse",
    "LoanCreate",
    "LoanRead",
    "UpdateAccountPath",
    "CategoryCreate",
    "CategoryUpdate",
    "CategoryRead",
    "ListCategoriesQuery",
    "CategoryPathParams",
    "CategoryListResponse",
    "TransactionCreate",
    "TransactionRead",
    "TransactionLegCreate",
    "TransactionLegRead",
    "TransactionListQuery",
    "TransactionListResponse",
    "LoanCreateRequest",
    "LoanUpdate",
    "LoanScheduleQuery",
    "LoanScheduleRead",
    "LoanEventRead",
    "LoanEventListQuery",
    "MonthlyReportQuery",
    "MonthlyReportEntry",
    "MonthlyReportResponse",
    "NetWorthHistoryQuery",
    "NetWorthHistoryResponse",
    "NetWorthPoint",
    "YearlyReportQuery",
    "YearlyReportEntry",
    "YearlyReportResponse",
    "TotalReportQuery",
    "TotalReportRead",
]
