"""Pydantic schemas for reporting API endpoints."""

from __future__ import annotations

from .reporting_models import (
    CashflowForecastResponse,
    DashboardOverviewResponse,
    DateRangeReportResponse,
    ExportReportResponse,
    MonthlyReportEntry,
    MonthlyReportResponse,
    NetWorthHistoryResponse,
    NetWorthPoint,
    NetWorthProjectionResponse,
    QuarterlyReportEntry,
    QuarterlyReportResponse,
    TotalOverviewResponse,
    TotalReportRead,
    TotalReportResponse,
    YearlyCategoryDetailResponse,
    YearlyOverviewRangeResponse,
    YearlyOverviewResponse,
    YearlyReportEntry,
    YearlyReportResponse,
)
from .reporting_queries import (
    CashflowForecastQuery,
    DashboardOverviewQuery,
    DateRangeReportQuery,
    ExportReportRequest,
    MonthlyReportQuery,
    NetWorthHistoryQuery,
    NetWorthProjectionQuery,
    QuarterlyReportQuery,
    TotalOverviewQuery,
    TotalReportQuery,
    YearlyCategoryDetailQuery,
    YearlyOverviewQuery,
    YearlyOverviewRangeQuery,
    YearlyReportQuery,
)

__all__ = [
    "MonthlyReportQuery",
    "YearlyReportQuery",
    "TotalReportQuery",
    "QuarterlyReportQuery",
    "DateRangeReportQuery",
    "MonthlyReportEntry",
    "MonthlyReportResponse",
    "YearlyReportEntry",
    "YearlyReportResponse",
    "QuarterlyReportEntry",
    "QuarterlyReportResponse",
    "DateRangeReportResponse",
    "TotalReportRead",
    "TotalReportResponse",
    "DashboardOverviewQuery",
    "DashboardOverviewResponse",
    "NetWorthHistoryQuery",
    "NetWorthPoint",
    "NetWorthHistoryResponse",
    "CashflowForecastQuery",
    "CashflowForecastResponse",
    "NetWorthProjectionQuery",
    "NetWorthProjectionResponse",
    "YearlyOverviewQuery",
    "YearlyOverviewRangeQuery",
    "YearlyOverviewResponse",
    "YearlyOverviewRangeResponse",
    "YearlyCategoryDetailQuery",
    "YearlyCategoryDetailResponse",
    "ExportReportRequest",
    "ExportReportResponse",
    "TotalOverviewQuery",
    "TotalOverviewResponse",
]
