"""initial schema"""

revision = 'e975ac53d694'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('account_type', sa.Enum('NORMAL', 'DEBT', 'INVESTMENT', name='accounttype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category_type', sa.Enum('INCOME', 'EXPENSE', 'ADJUSTMENT', 'LOAN', 'INTEREST', name='categorytype'), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(length=16), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('investment_snapshots',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=False),
    sa.Column('report_type', sa.String(length=80), nullable=True),
    sa.Column('account_name', sa.String(length=160), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('portfolio_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('parsed_payload', sa.JSON(), nullable=False),
    sa.Column('cleaned_payload', sa.JSON(), nullable=True),
    sa.Column('bedrock_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.Enum('RETAINED_EARNINGS', 'INTEREST_EXPENSE', 'UNASSIGNED', name='systemaccountcode'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('transaction_import_batches',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_name', sa.String(length=160), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balance_snapshots',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'captured_at', name='uq_balance_snapshot')
    )
    op.create_table('budgets',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', name='budgetperiod'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'period', name='uq_budget_category_period')
    )
    op.create_table('import_files',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=160), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('bank_type', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['transaction_import_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment_holdings',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('account_name', sa.String(length=160), nullable=True),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('isin', sa.String(length=48), nullable=True),
    sa.Column('holding_type', sa.String(length=32), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('value_sek', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['investment_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id', 'name', 'currency', name='uq_investment_holding_snapshot_name_currency')
    )
    op.create_table('loans',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('origin_principal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('current_principal', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('interest_rate_annual', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('interest_compound', sa.Enum('DAILY', 'MONTHLY', 'YEARLY', name='interestcompound'), nullable=False),
    sa.Column('minimum_payment', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('expected_maturity_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('subscriptions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('matcher_text', sa.String(length=255), nullable=False),
    sa.Column('matcher_amount_tolerance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('matcher_day_of_month', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_errors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['import_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_rows',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('suggested_category', sa.String(length=160), nullable=True),
    sa.Column('suggested_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('suggested_reason', sa.String(length=500), nullable=True),
    sa.Column('suggested_subscription_id', sa.UUID(), nullable=True),
    sa.Column('suggested_subscription_name', sa.String(length=160), nullable=True),
    sa.Column('suggested_subscription_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('suggested_subscription_reason', sa.String(length=500), nullable=True),
    sa.Column('transfer_match', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['import_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_rate_changes',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('new_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('created_source', sa.Enum('MANUAL', 'IMPORT', 'SYSTEM', name='createdsource'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('transaction_type', sa.Enum('INCOME', 'EXPENSE', 'TRANSFER', 'ADJUSTMENT', 'INVESTMENT_EVENT', name='transactiontype'), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(length=180), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('RECORDED', 'IMPORTED', 'REVIEWED', 'FLAGGED', name='transactionstatus'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['transaction_import_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id'),
    sa.UniqueConstraint('occurred_at', 'description', 'external_id', name='uq_transaction_identity')
    )
    op.create_table('investment_transactions',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transaction_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('holding_name', sa.String(length=240), nullable=True),
    sa.Column('isin', sa.String(length=48), nullable=True),
    sa.Column('account_name', sa.String(length=160), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('amount_sek', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('fee_sek', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('ledger_transaction_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['ledger_transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['investment_snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('occurred_at', 'transaction_type', 'description', 'amount_sek', 'quantity', name='uq_investment_tx_identity')
    )
    op.create_table('transaction_legs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('running_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_events',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('loan_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('transaction_leg_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('DISBURSEMENT', 'PAYMENT_PRINCIPAL', 'PAYMENT_INTEREST', 'INTEREST_ACCRUAL', 'FEE', name='loaneventtype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_leg_id'], ['transaction_legs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_events')
    op.drop_table('transaction_legs')
    op.drop_table('investment_transactions')
    op.drop_table('transactions')
    op.drop_table('loan_rate_changes')
    op.drop_table('import_rows')
    op.drop_table('import_errors')
    op.drop_table('goals')
    op.drop_table('subscriptions')
    op.drop_table('loans')
    op.drop_table('investment_holdings')
    op.drop_table('import_files')
    op.drop_table('budgets')
    op.drop_table('balance_snapshots')
    op.drop_table('transaction_import_batches')
    op.drop_table('system_accounts')
    op.drop_table('investment_snapshots')
    op.drop_table('categories')
    op.drop_table('accounts')
    # ### end Alembic commands ###
