#!/usr/bin/env python3
"""Populate the web app .env file with Cognito outputs from Terraform."""
from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path
from typing import Any, Dict


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--tf-dir",
        default="infra/terraform",
        help="Terraform working directory (defaults to infra/terraform)",
    )
    parser.add_argument(
        "--env-path",
        default="apps/web/.env",
        help="Path to the base env file that should be updated (production defaults)",
    )
    parser.add_argument(
        "--env-local-path",
        default="apps/web/.env.local",
        help="Path to the local env file that should be updated",
    )
    parser.add_argument(
        "--env-production-path",
        default="apps/web/.env.production",
        help="Path to the production env file that should be updated",
    )
    parser.add_argument(
        "--aws-region",
        default="eu-north-1",
        help="AWS region used to resolve SSM parameters",
    )
    parser.add_argument(
        "--aws-profile",
        default="",
        help="Optional AWS CLI profile for the terraform outputs and SSM queries",
    )
    parser.add_argument(
        "--local-redirect-signin",
        default="http://localhost:5173/login",
        help="Override for VITE_OAUTH_REDIRECT_SIGNIN in .env.local",
    )
    parser.add_argument(
        "--local-redirect-signout",
        default="http://localhost:5173/login",
        help="Override for VITE_OAUTH_REDIRECT_SIGNOUT in .env.local",
    )
    return parser.parse_args()


def run_subprocess(command: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(command, check=True, capture_output=True, text=True)


def read_auth_parameter_paths(tf_dir: str, profile: str) -> Dict[str, str]:
    command = ["terraform", f"-chdir={tf_dir}", "output", "-json", "auth_parameter_paths"]
    result = run_subprocess(command)

    output: Any = json.loads(result.stdout)
    if isinstance(output, dict):
        value = output.get("value", output)
    else:
        value = output

    if not isinstance(value, dict):
        raise RuntimeError("Unexpected terraform output for `auth_parameter_paths`.")

    expected_keys = {"user_pool_id", "user_pool_client"}
    missing = expected_keys.difference(value.keys())
    if missing:
        raise RuntimeError(
            "Terraform output `auth_parameter_paths` missing keys: " + ", ".join(sorted(missing))
        )

    return {key: str(value[key]) for key in expected_keys}


def read_parameter(name: str, region: str, profile: str) -> str:
    command = [
        "aws",
        "ssm",
        "get-parameter",
        "--name",
        name,
        "--with-decryption",
        "--query",
        "Parameter.Value",
        "--output",
        "text",
        "--region",
        region,
    ]
    if profile:
        command.extend(["--profile", profile])
    result = run_subprocess(command)
    return result.stdout.strip()


def read_oauth_settings(tf_dir: str, profile: str) -> dict:
    command = ["terraform", f"-chdir={tf_dir}", "output", "-json", "auth_oauth_settings"]
    result = run_subprocess(command)
    output: Any = json.loads(result.stdout)
    return output.get("value", output)


def _parse_existing_env(env_path: Path) -> dict[str, str]:
    if not env_path.exists():
        return {}
    env_data: dict[str, str] = {}
    for line in env_path.read_text(encoding="utf-8").splitlines():
        if "=" not in line or line.strip().startswith("#"):
            continue
        key, _, value = line.partition("=")
        env_data[key.strip()] = value.strip()
    return env_data


def write_env_file(
    env_path: Path,
    region: str,
    user_pool_id: str,
    user_pool_client_id: str,
    oauth_settings: dict,
    *,
    redirect_signin: str | None = None,
    redirect_signout: str | None = None,
) -> None:
    existing = _parse_existing_env(env_path)
    api_base = existing.get("VITE_API_BASE_URL", "")
    fallback_signin = oauth_settings.get("callback_urls", [""])[0]
    fallback_signout = oauth_settings.get("logout_urls", [""])[0]
    redirect_signin = redirect_signin or fallback_signin
    redirect_signout = redirect_signout or fallback_signout

    env_path.parent.mkdir(parents=True, exist_ok=True)
    content = (
        "# Auto-generated by script. Do not edit manually.\n"
        f"VITE_AWS_REGION={region}\n"
        f"VITE_USER_POOL_ID={user_pool_id}\n"
        f"VITE_USER_POOL_CLIENT_ID={user_pool_client_id}\n"
        f"VITE_COGNITO_DOMAIN={oauth_settings.get('domain', '')}\n"
        f"VITE_OAUTH_REDIRECT_SIGNIN={redirect_signin}\n"
        f"VITE_OAUTH_REDIRECT_SIGNOUT={redirect_signout}\n"
        f"VITE_API_BASE_URL={api_base}\n"
    )
    env_path.write_text(content, encoding="utf-8")


def main() -> None:
    args = parse_args()

    base_env_path = Path(args.env_path)
    local_env_path = Path(args.env_local_path)
    prod_env_path = Path(args.env_production_path)

    existing_env = _parse_existing_env(base_env_path)
    existing_local_env = _parse_existing_env(local_env_path)
    existing_prod_env = _parse_existing_env(prod_env_path)

    def first_present(key: str) -> str:
        for source in (existing_env, existing_local_env, existing_prod_env):
            if key in source and source[key]:
                return source[key]
        return ""

    auth_paths = read_auth_parameter_paths(args.tf_dir, args.aws_profile)
    try:
        oauth_settings = read_oauth_settings(args.tf_dir, args.aws_profile)
    except subprocess.CalledProcessError as error:
        fallback_domain = first_present("VITE_COGNITO_DOMAIN")
        fallback_signin = first_present("VITE_OAUTH_REDIRECT_SIGNIN")
        fallback_signout = first_present("VITE_OAUTH_REDIRECT_SIGNOUT")
        if not fallback_domain:
            raise RuntimeError(
                "Failed to read oauth settings from terraform output and no fallback found in existing env files."
            ) from error
        print("Warning: using existing OAuth settings from env as fallback", flush=True)
        oauth_settings = {
            "domain": fallback_domain,
            "callback_urls": [fallback_signin],
            "logout_urls": [fallback_signout],
        }

    try:
        user_pool_id = read_parameter(auth_paths["user_pool_id"], args.aws_region, args.aws_profile)
    except subprocess.CalledProcessError as error:
        fallback = first_present("VITE_USER_POOL_ID")
        if not fallback:
            raise RuntimeError(
                "Failed to read user pool id from SSM and no fallback found in existing env files."
            ) from error
        print("Warning: using existing VITE_USER_POOL_ID from env as fallback", flush=True)
        user_pool_id = fallback

    try:
        user_pool_client_id = read_parameter(
            auth_paths["user_pool_client"], args.aws_region, args.aws_profile
        )
    except subprocess.CalledProcessError as error:
        fallback = first_present("VITE_USER_POOL_CLIENT_ID")
        if not fallback:
            raise RuntimeError(
                "Failed to read user pool client id from SSM and no fallback found in existing env files."
            ) from error
        print(
            "Warning: using existing VITE_USER_POOL_CLIENT_ID from env as fallback",
            flush=True,
        )
        user_pool_client_id = fallback

    env_path = Path(args.env_path)
    env_local_path = Path(args.env_local_path)
    env_prod_path = Path(args.env_production_path)

    write_env_file(
        env_path,
        args.aws_region,
        user_pool_id,
        user_pool_client_id,
        oauth_settings,
    )

    write_env_file(
        env_prod_path,
        args.aws_region,
        user_pool_id,
        user_pool_client_id,
        oauth_settings,
    )

    write_env_file(
        env_local_path,
        args.aws_region,
        user_pool_id,
        user_pool_client_id,
        oauth_settings,
        redirect_signin=args.local_redirect_signin,
        redirect_signout=args.local_redirect_signout,
    )

    print(
        f"Updated {env_path}, {env_local_path}, and {env_prod_path} with Cognito configuration."
    )


if __name__ == "__main__":
    main()
